import Foundation

@MainActor enum WorkspaceSessionRegression {
    static func run() throws {
        try CodexRegression.expect(WorkspaceFileLink.resolve("outputs/report%20draft.pdf", cwd: "/fixture/project")?.path == "/fixture/project/outputs/report draft.pdf", "relative Markdown file links use the conversation directory")
        try CodexRegression.expect(WorkspaceFileLink.resolve("/fixture/source.swift:12:3#L12", cwd: "/fixture")?.path == "/fixture/source.swift", "source-line suffixes do not become part of the preview filename")
        try CodexRegression.expect(WorkspaceFileLink.resolve("https://example.invalid/a?q=1", cwd: "/fixture")?.absoluteString == "https://example.invalid/a?q=1", "web links keep their original target")
        try CodexRegression.expect(WorkspaceFileLink.resolve("javascript:alert(1)", cwd: "/fixture") == nil && WorkspaceFileLink.resolve("file://other-host/share/file", cwd: "/fixture") == nil, "non-web schemes and network file URLs are not opened")
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("claudex-session-state-" + UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: root) }
        let source = ThreadStore(storageDirectory: root)
        source.restoreLocalWorkspace()
        let id = source.newThread(cwd: "/fixture/project", engine: .codex)
        source.selectedController?.composerDraft = "继续修复验证失败，保留这段未发送内容"
        let attachment = ComposerAttachment(id: "pasted-fixture", kind: .image, name: "sample.png", imageData: Data([1, 2, 3]), mediaType: "image/png")
        source.selectedController?.restoreComposerDraft(text: "继续修复验证失败，保留这段未发送内容", attachments: [attachment])
        source.rememberProject("/fixture/project")
        source.rememberProject("/fixture/other")
        source.rememberProject("/fixture/project")
        source.persistWorkspaceNow()
        let persisted = try WorkspaceSessionState.load(from: root.appendingPathComponent("workspace-session.json"))!
        try CodexRegression.expect(persisted.composers.count == 1 && persisted.projects.count == 2, "draft and projects persisted once")
        let mode = try FileManager.default.attributesOfItem(atPath: root.appendingPathComponent("workspace-session.json").path)[.posixPermissions] as? Int
        try CodexRegression.expect(mode == 0o600, "drafts containing pasted images have private permissions")
        let restored = ThreadStore(storageDirectory: root)
        restored.restoreLocalWorkspace()
        try CodexRegression.expect(restored.selectedId == id && restored.selectedController?.engine == .codex, "relaunch restores selected native engine and draft identity without launching it")
        try CodexRegression.expect(restored.selectedController?.composerDraft == "继续修复验证失败，保留这段未发送内容" && restored.selectedController?.attachments.first?.imageData == Data([1, 2, 3]), "relaunch restores text and clipboard image bytes")
        let next = restored.newThread()
        try CodexRegression.expect(next != id && restored.controllers[id]?.composerDraft.isEmpty == false, "new chat never reuses a draft with unsent content")
        try CodexRegression.expect(restored.selectedController?.cwd == "/fixture/project", "new chat retains current project")
        restored.hide(id)
        try CodexRegression.expect(restored.hiddenThreads.contains { $0.id == id }, "hidden draft remains recoverable")
        restored.restoreHidden(id)
        try CodexRegression.expect(!restored.hiddenThreads.contains { $0.id == id } && restored.groups.flatMap(\.threads).contains { $0.id == id }, "restored draft returns to sidebar")
        try CodexRegression.expect(restored.groups.contains { $0.cwd == "/fixture/other" && $0.threads.isEmpty }, "saved empty projects appear in project groups")
        restored.persistWorkspaceNow()
        let nativeRoot = root.appendingPathComponent("native")
        let record = SessionRecord(id: "codex:fixture", cwd: "/fixture/project", title: "Native conversation", createdAt: Date(), updatedAt: Date(), path: "/fixture/not-read.jsonl", fileSize: 1, fileModified: Date(), engine: .codex)
        let native = ConversationController(id: record.id, cwd: record.cwd, settings: ThreadSettings(engine: .codex), hasSessionFile: true, sessionPath: record.path)
        native.restoreComposerDraft(text: "未发送的原生会话后续", attachments: [attachment])
        let owner = ThreadStore(snapshot: .init(records: [record], controllers: [native], selectedId: record.id), storageDirectory: nativeRoot)
        owner.persistWorkspaceNow()
        owner.hide(record.id)
        try CodexRegression.expect(owner.controllers[record.id]?.composerDraft == "未发送的原生会话后续", "hiding an existing native conversation preserves its composer")
        let savedOverrides = try JSONDecoder.standard.decode([String: ThreadOverride].self, from: Data(contentsOf: nativeRoot.appendingPathComponent("threads.json")))
        let relaunched = ThreadStore(snapshot: .init(records: [record], overrides: savedOverrides), storageDirectory: nativeRoot)
        relaunched.restoreLocalWorkspace()
        try CodexRegression.expect(relaunched.hiddenThreads.contains { $0.id == record.id }, "native hidden state survives reload")
        relaunched.restoreHidden(record.id)
        try CodexRegression.expect(relaunched.controllers[record.id]?.composerDraft == "未发送的原生会话后续" && relaunched.controllers[record.id]?.attachments.first?.imageData == Data([1, 2, 3]), "restoring existing native conversation after relaunch retains text and pasted image")
        let edited = ConversationController(id: record.id, cwd: record.cwd, settings: ThreadSettings(engine: .codex), hasSessionFile: true, sessionPath: record.path)
        edited.composerDraft = "启动期间的新输入"
        let concurrent = ThreadStore(snapshot: .init(records: [record], controllers: [edited], selectedId: record.id), storageDirectory: nativeRoot)
        concurrent.restoreLocalWorkspace()
        try CodexRegression.expect(concurrent.controllers[record.id]?.composerDraft == "启动期间的新输入", "delayed restore cannot overwrite input entered during startup")
        concurrent.persistWorkspaceNow()
        let newestState = try WorkspaceSessionState.load(from: nativeRoot.appendingPathComponent("workspace-session.json"))!
        try CodexRegression.expect(newestState.composers.first { $0.id == record.id }?.text == "启动期间的新输入", "the latest in-memory draft wins in the next durable snapshot")
        let broken = root.appendingPathComponent("broken")
        try FileManager.default.createDirectory(at: broken, withIntermediateDirectories: true)
        let brokenURL = broken.appendingPathComponent("workspace-session.json")
        let malformed = Data("malformed workspace".utf8)
        try malformed.write(to: brokenURL)
        let isolated = ThreadStore(storageDirectory: broken)
        isolated.restoreLocalWorkspace()
        isolated.newThread(cwd: "/fixture")
        isolated.persistWorkspaceNow()
        let preserved = try Data(contentsOf: brokenURL)
        try CodexRegression.expect(isolated.workspaceError != nil && preserved == malformed, "unreadable state is reported and never overwritten")
        print("PASS — durable drafts, projects, hidden-session recovery and corrupted-state preservation")
    }
}
